### PR TITLE
Added missing package tasks

### PR DESCRIPTION
**Pull request by ferrums**
Added PackageInstallTask, and PackageInstallTaskBase.

Correct types for SwIPC are missing.

### CODE REVIEW

**Comment by SciresM** [comment]
What service hosts these? I haven't seen any sign of these APIs in e.g. NCM.

**Comment by ferrums** [comment]
I don't know, they are symbols in DevMenuApplication.

**Comment by misson20000** [comment]
I'd hold off on adding these to SwIPC until we can figure out what the rawdata/buffers are.

**Comment by misson20000** [comment]
Going to close this, since we don't have exact definitions for these.

**Pull request closed without merging**
