### PR TITLE
Auto-RB

### PR DESCRIPTION
**Pull request by misson20000**
This includes my new `auto.id` generator, some README updates, and a few syntax changes.

The new generator tries to *never* be wrong. It may not always be useful, but it should never be incorrect. When we have information on sizes of individual arguments but not actual type information, types such as `i8`, `i16`, `i32`, and `i64` are used, with any larger types or types that are not aligned in the way one might expect represented as `bytes`. When we do not have individual argument information, all arguments are represented by `unknown<total size>`. In the hypothetical case that we didn't have even this information, we would use `unknown`.

TODO:
- [ ] Review new `auto.id` for any potential issues
- [ ] Review manually created `.id` files for correctness
- [x] Review syntax/semantics changes
  - [x] Decorators are allowed on type/interface definitions
  - [x] `KHandle`/`KObject` -> `handle<copy|move[, type]>`
  - [x] New `b8` type
  - [x] ~~`buffer<_, _, 0>` -> `buffer<_, _, variable>`~~
  - [x] ~~New `buffer<data, _>` type, for unsized raw data transfers~~
  Indicate unsized raw data transfers using `buffer<bytes, _>`
  - [x] ~~We actually use `array<type, transfer>` now~~
  Emit array-buffers using `buffer<type[], _>` syntax
  - [x] `bytes<size[, alignment]>`
  - [x] Shorten `buffer<data_type, transfer_type, size>` to `buffer<data_type, transfer_type>`
    - Emit `buffer<unknown<size>, transfer_type>` when `size` is known but `data_type` isn't
- [ ] Service registration
- [x] Fixups
  - [x] idparser
  - [x] gendocs

### CODE REVIEW

**Comment by roblabla** [comment]
A couple thoughts:

1. What's the difference between data and bytes<0x200> ? Maybe we could have bytes<variable> instead of data ? In general, I'd really like to avoid adding "special" types that only make sense in special contexts.

2. Could we please deprecate array<> as a buffer alias? I find it super disgusting. There should only be a single buffer type. And array<type, num> should just be a raw data type to denote an array of num items of the given type.

3. Why do buffers have a size ? They should be able to infer the size from the underlying datatype. They don't really make sense IMO - I guess they could make sense as a way to ensure the underlying data type is of the right size for a potential verifier, but meh. I'd rather have `buffer<unknown<5>, 0x20>`. This also means code generators will be able to really treat buffers as simply a pointer to some type of raw data, and treat raw data and buffers essentially the same.

**Comment by misson20000** [comment]
Data is unsized, for things like sending data over sockets instead of transferring structured data with a specific size. Perhaps bytes with no specialization would be better? Array isn't quite a buffer alias because it has slightly different meaning, but perhaps buffer<type[], transfer_type>? I'll respond to the other points when I have more time.

**Comment by misson20000** [comment]
Alright, here's a better response.

1. `data` represents an unsized, untyped amount of raw data. Unspecialized `bytes` would be a suitable replacement, as in `buffer<bytes, 0x21>`.

2. Array comes from the `args` strings, which represent those buffers using templates called `InArray` and `OutArray`. I strongly disagree with `array<type, num>` being a raw data type. It would be very confusing to tell between SwIPC files that use `array` as a buffer and `array` as a raw data. Raw data should use C-style syntax, as in `u64[8]`. As for array-buffers, I'd be okay with `buffer<type[], transfer_type` as in `[2] ListAllUsers() -> array<nn::account::Uid[], 0xa>`. I know that in C, the brackets go after the name of the variable. I think that in SwIPC, they belong next to the type, as they are type information in SwIPC and it simplifies type parsing.

3. I agree that the sizes on buffers are redundant. It *is* very convenient to know how big the type is without having to look it up. We should add alt-text or something similarly convenient to the HTML docs showing how big a given type is when you hover over it. We'll have to be careful for the cases that don't look like `buffer<type, _, sizeof(type)>` though. `buffer<unknown, _>` will have to be distinct from `buffer<bytes, _>` in that the former has an unknown size, whereas the latter has a variable size.

Do the rest of the items under syntax/semantics changes look good?

**Comment by roblabla** [comment]
1. Makes sense. I'd prefer that, yes. In C-lang, this means that bytes is a DST (Dynamically-Sized Type), like `char[]`.

2. I agree that [] should go with the type, and I'd feel a lot better about buffer<type[]> than array<type>, as it's more general and can be used in raw data and structs.

3. I agree it's super convenient. But calculating the size from the struct is pretty easy (Just have to sum the size of each type, with some care taken for alignment), and making it show up as an alt text or even directly in the docs can be done easily.

The rest of the changes look really good!

**Comment by misson20000** [comment]
Hmm, regarding removing the size field from buffers:

If a type changes size, but a command using that type in a buffer stays the same, (how) should we indicate that that has changed? Currently, in such a case, we emit this:
```
@version(2.0.0)
type nn::account::nas::NasUserBase = bytes<0x24b, unknown>;
@version(3.0.0+)
type nn::account::nas::NasUserBase = bytes<0x24f, unknown>;
...
interface nn::account::baas::IAdministrator {
    ...
    @version(1.0.0-2.0.0)
    [130] GetNintendoAccountUserResourceCache() -> (nn::account::NintendoAccountId, buffer<nn::account::nas::NasUserBase, 0x1a>, buffer<bytes, 0x6>);
    @version(3.0.0+)
    [130] GetNintendoAccountUserResourceCache() -> (nn::account::NintendoAccountId, buffer<nn::account::nas::NasUserBase, 0x1a>, buffer<bytes, 0x6>);
    ...
}
```
Here it's already hard to tell what has changed between the two versions, but if we combined them into one definition, there would be no indication that anything has changed at all. Thoughts?

**Comment by roblabla** [comment]
@misson20000 IMO, this could be further simplified to this:

```
@version(2.0.0)
type nn::account::nas::NasUserBase = bytes<0x24b, unknown>;
@version(3.0.0+)
type nn::account::nas::NasUserBase = bytes<0x24f, unknown>;
...
interface nn::account::baas::IAdministrator {
    ...
    [130] GetNintendoAccountUserResourceCache() -> (nn::account::NintendoAccountId, buffer<nn::account::nas::NasUserBase, 0x1a>, buffer<bytes, 0x6>);
    ...
}
```

(Well, ideally those typedefs should be structs but yeah :P).

And people to go check out the NasUserBase to find out it changes between version. In the SwIPC docs, we could use some color code or something to indicate it's a version-dependant type.

**Pull request merged**
